registration:
 Ping:
  - Conversation
 Greet:
  - Conversation
 Shutdown:
  - System
 ChangeLightState:
  - Shield
 ChangeLightColor:
  - Shield
 SetTimer:
  - Timer
 RemoveTimer:
  - Timer
 QueryTimer:
  - Timer